name: RunningTests

on: [push]

jobs:
  running-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - name: Setup Golang Environment
        uses: actions/setup-go@v1
        with:
          go-version: 1.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: |
          GO111MODULE=off GOBIN=$(pwd)/bin go get golang.org/x/lint/golint
          bin/golint -set_exit_status ./...
        if: "matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'"
      - name: Prepare test
        env:
          TOKEN: ${{ secrets.GITHUB_TEST_TOKEN }}
        run: echo "GITHUB_ACCESS_TOKEN=$TOKEN" > testdata/github-actions-env.env
      - name: Run Tests
        run: make test
